
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # Thses are replica set labels
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec: 
  replicas: 1
  selector:
    # These labels are used to select pods
    matchLabels:
       project: roboshop
       component: frontend
       tier: frontend
  # Pod definition    
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        tier: frontend
    spec: 
      containers: 
      - name: frontend
        image: pradeepreddy90/frontend:v1
   
        ports:
        - name: liveness-port
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec: 
  type: LoadBalancer 
  selector: 
   project: roboshop
   component: frontend
   tier: frontend
  ports: 
    - protocol: TCP
      port: 80 # service Port
      targetPort: 80  # Container Port
        