apiVersion: v1
kind : ConfigMap
metadata: 
  name: shipping
data: 
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # Thses are replica set labels
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec: 
  replicas: 1
  selector:
    # These labels are used to select pods
    matchLabels:
       project: roboshop
       component: shipping
       tier: backend
  # Pod definition    
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend
    spec: 
      containers: 
      - name: shipping
        image: pradeepreddy90/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec: 
  selector: 
   project: roboshop
   component: shipping
   tier: backend
  ports: 
    - protocol: TCP
      port: 8080 # service Port
      targetPort: 8080  # Container Port
        