apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # Thses are replica set labels
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
spec: 
  replicas: 1
  selector:
    # These labels are used to select pods
    matchLabels:
       project: roboshop
       component: rabbitmq
       tier: db
  # Pod definition    
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: db
    spec: 
      containers: 
      - name: rabbitmq
        image: pradeepreddy90/rabbitmq:v1
        imagePullPolicy: Always 
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec: 
  selector: 
   project: roboshop
   component: rabbitmq
   tier: db
  ports: 
    - protocol: TCP
      port: 27017 # service Port
      targetPort: 27017  # Container Port
        