apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # Thses are replica set labels
  labels:
    project: roboshop
    component: mysql
    tier: db
spec: 
  replicas: 1
  selector:
    # These labels are used to select pods
    matchLabels:
       project: roboshop
       component: mysql
       tier: db
  # Pod definition    
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec: 
      containers: 
      - name: mysql
        image: pradeepreddy90/mysql:v1
        imagePullPolicy: Always 
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 40
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec: 
  selector: 
   project: roboshop
   component: mysql
   tier: db
  ports: 
    - protocol: TCP
      port: 3306 # service Port
      targetPort: 3306  # Container Port
        